services:
  qdrant-source:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 7333:6333
      - 7334:6334
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
  qdrant-target:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 8333:6333
      - 8334:6334
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
