name: Merged to Main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  merged-to-main:
    name: Merged to Main

    runs-on: ubuntu-latest

    steps:
      - name: Pull Main Branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Update Release Draft
        uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0 # v7.6.0
        with:
          disable-autolabeler: true
          commitish: main
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
