name: Release

on:
  push:
    branches:
      - 'releases/**'

jobs:
  Release:
    name: Release Workflow
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      pull-requests: write
      id-token: write # needed for cosign keyless signing with OIDC
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract build info
        id: extract_build_info
        run: |
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "commit_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry.cloud.qdrant.io
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.qdrant.io
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            registry.cloud.qdrant.io/library/qdrant-migration
          tags: |
            type=raw,value=${{ steps.extract_build_info.outputs.tag }}
            type=raw,value=latest

      - name: Build and push container image
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          context: .
          push: true
          sbom: true
          provenance: true
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            VERSION=${{ steps.extract_build_info.outputs.tag }}
            BUILD=${{ steps.extract_build_info.outputs.commit_short }}

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.9.1

      - name: Sign container image at registry.cloud.qdrant.io
        run: |
          cosign sign --yes "${TAGS}@${DIGEST}"
        env:
          TAGS: registry.cloud.qdrant.io/library/qdrant-migration:${{ steps.extract_build_info.outputs.tag }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}

      - name: Tag Release
        shell: bash
        run: |
          git tag ${{ steps.extract_build_info.outputs.tag }}
          git push origin ${{ steps.extract_build_info.outputs.tag }}

      - name: Publish Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
          commitish: ${{ github.ref }}
          tag: ${{ steps.extract_build_info.outputs.tag }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
